name: reminderflutter
description: "App de lembretes com notificações"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_local_notifications: ^17.2.3  # ← Substitui awesome_notifications
  timezone: ^0.9.4  # ← Necessário para agendamento
  sqflite: ^2.3.3+1
  path: ^1.9.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3 # ADICIONADO: Para salvar preferência de tema
  flutter_colorpicker: ^1.1.0 # Ou a versão mais recente que encontrar
  file_picker: # Ou a versão mais recente
  path_provider: ^2.1.3 # Ou a versão mais recente
  permission_handler: ^11.3.1 # Ou a versão mais recente
  # intl: ^0.19.0 # (Opcional, se DateFormat der problema)


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

