name: seuslembretes
description: "App de lembretes com notificações"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_local_notifications: ^17.2.3
  timezone: ^0.9.4
  sqflite: ^2.3.3+1
  path: ^1.9.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.3
  flutter_colorpicker: ^1.1.0 # Versão especificada
  file_picker: ^10.1.9 # Atualizado para versão mais recente
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  flutter_timezone: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/lembretes.png"

flutter:
  uses-material-design: true

