name: reminderflutter
description: "App de lembretes com notificações"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_local_notifications: ^17.2.3  # ← Substitui awesome_notifications
  timezone: ^0.9.4  # ← Necessário para agendamento
  permission_handler: ^11.3.1  # ← ADICIONE esta linha
  sqflite: ^2.3.3+1
  path: ^1.9.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true